# Generated by Django 3.2.8 on 2022-03-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EditableSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_post_lifespan', models.IntegerField(default=7)),
                ('user_post_lifespan', models.IntegerField(default=30)),
                ('like_lifespan_add', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Editable Settings',
            },
        ),
    ]
