# Generated by Django 3.2.8 on 2022-03-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagimage',
            name='image',
            field=models.ImageField(upload_to='tag_images/'),
        ),
    ]
