# Generated by Django 3.2.8 on 2022-03-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
