# Generated by Django 3.2.8 on 2022-03-27 05:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bantime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
